#pragma config(Motor,  port1,           WLift,         tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port2,           FLDrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Wrist,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FRDrive,       tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          ELift,         tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

//VARIABLES
int maxSpeed = 127;
float encoderInches = 0;
float inchesToTicks(float inches);
bool infiniteConveyor = false;

//FORWARD DECLARATIONS
void arcadeDrive();
void RightDrive(int speed);
void LeftDrive(int speed);

void arcadeDrive()
{
	int motorPower = vexRT[Ch3];
	int turnPower = vexRT[Ch1];

	//DRIVE
	if (abs(vexRT[Ch3]) > 45)
	{
		motor[FLDrive] = motorPower;
		//motor[BLDrive] = motorPower;

		motor[FRDrive] = motorPower;
	//	motor[BRDrive] = motorPower;
  }
  else if (abs(vexRT[Ch1]) > 45)
	{                                                                                                                                                                                                                                                                   ;
		motor[FRDrive] = -turnPower;

		motor[FLDrive] = turnPower;
  }
  else
  {
  	motor[FLDrive] = 0;
		motor[FRDrive] = 0;

  }

  //Claw
  if (vexRT[Btn5U] == 1)
	{
		motor[Claw] = -60;
	}
	else if (vexRT[Btn5D] == 1)
	{
		motor[Claw] = 60;
	}
	else
	{
		motor[Claw] = 0;
	}

  //Claw
  if (vexRT[Btn7R] == 1)
	{
		motor[Wrist] = -100;
	}
	else if (vexRT[Btn7D] == 1)
	{
		motor[Wrist] = 35;
	}
	else
	{
		motor[Wrist] = 15;
	}

	//Lift
	if (vexRT[Btn6U] == 1)
	{
		motor[WLift] = motor[ELift] =  110;
	}
	else if (vexRT[Btn6D] == 1)
	{
		motor[WLift] = motor[ELift] =  -75;
	}
	else
	{
		motor[WLift] = motor[ELift] =  25;
	}

}



void RightDrive(int speed)
{
	motor[FRDrive] = speed;
}

void LeftDrive(int speed)
{
	motor[FLDrive] = speed;
}

////////////////////////////Main Task
task main()
{
	while(true){
		arcadeDrive();
	}
}

